version: 2.1
executors:
  node-with-db-executor:
    docker:
      - image: cimg/node:lts
        auth:
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
      - image: mariadb
        auth:
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
        environment:
          MARIADB_ROOT_PASSWORD: test
          MARIADB_DATABASE: test
  basic-node-executor:
    docker:
      - image: cimg/node:lts
        auth:
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
      - image: mariadb
        auth:
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
        environment:
          MARIADB_ROOT_PASSWORD: test
          MARIADB_DATABASE: test
jobs:
  unit-tests:
    executor: basic-node-executor
    steps:
      - checkout
      - run: |
          npm install
          node --version
          npm test
  component-and-e2e-tests:
    executor: node-with-db-executor
    steps:
      - checkout 
      - run: |
          npm install
          node --version
          printf "MARIADB_HOST=\"127.0.0.1\"\nMARIADB_PORT=\"3306\"\nMARIADB_USER=\"root\"\nMARIADB_PASS=\"test\"\nMARIADB_DB=\"test\"" > .env
          npm run component-test && npm run e2e-test
workflows:
  my-custom-workflow:
    jobs:
      - unit-tests
      - component-and-e2e-tests
